// src/models/Applicant.ts
import mongoose, { Schema, Document } from 'mongoose';

/**
 * Interface representing the structure of an Applicant document in MongoDB.
 */
export interface IApplicant extends Document {
    name: string;
    email: string;
    cvBuffer: Buffer; // Original uploaded .docx file content
    cvText?: string; // Plain text extracted from the CV by Mammoth
    cvSummary?: string; // Summary generated by Gemini API (or error message)
    createdAt: Date;
    updatedAt: Date;
}

const ApplicantSchema: Schema<IApplicant> = new Schema({
    name: {
        type: String,
        required: [true, 'Applicant name is required.'],
        trim: true,
        index: true, // Index for potential sorting/searching
    },
    email: {
        type: String,
        required: [true, 'Applicant email is required.'],
        unique: true, // Ensure no duplicate applications via email
        lowercase: true,
        trim: true,
        match: [/^[^\s@]+@[^\s@]+\.[^\s@]+$/, 'Please provide a valid email address.'], // Basic email format validation
        index: true, // Essential for performance on lookups/uniqueness check
    },
    cvBuffer: {
        type: Buffer,
        required: [true, 'CV file buffer is required.'],
        select: false, // Often don't need to retrieve the full buffer unless downloading
    },
    cvText: {
        type: String, // Text extracted locally
        select: false, // Might be large, select only when needed for processing
    },
    cvSummary: {
        type: String, // Text generated by Gemini
    },
}, {
    timestamps: true // Automatically adds createdAt and updatedAt fields
});

// Ensure the model is only compiled once
export default mongoose.models.Applicant as mongoose.Model<IApplicant> || mongoose.model<IApplicant>('Applicant', ApplicantSchema);